# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Music Magic Server (non-free) Unofficial installer"
  org.opencontainers.image.description: "Installer for Music Magic Server for MusicIP into a HA addon"
  org.opencontainers.image.source: "https://github.com/pssc/ha-addon-mip/mmserver"
  org.opencontainers.image.licenses: "Multiple"
